version: '3'

services:
    mysql-server:
        image: mysql:8
        ports:
            - "13306:3306"     
        environment:
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress_user
            MYSQL_PASSWORD: secret
    wordpress:
        image: wordpress:latest
        ports:
            - "20080:80"
        environment:
            WORDPRESS_DB_HOST: mysql-server:3306
            WORDPRESS_DB_USER: wordpress_user
            WORDPRESS_DB_PASSWORD: secret
        depends_on:
            - mysql-server            
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 30080:80
        environment:
            PMA_HOST: 'mysql-server'
            PMA_PORT: '3306'
            PMA_USER: 'wordpress_user'
            PMA_PASSWORD: "secret"
        depends_on:
            - mysql-server
